
/*
===========================================================================
Copyright (C) GAMbit Software (www.gambit-software.com)
===========================================================================
*/

#ifndef __MANAGER_H__
#define __MANAGER_H__

/*
#include <vector>

template<typename T>
class manager_t
{
public:
	typedef std::vector<T> list_t;
	list_t list;

	inline manager_t()
	{
	}

	virtual ~manager_t();
	{
		for ( list_t::const_iterator i = list.begin(); i != list.end(); i++ )
				delete (*i);
	}


private:
	inline manager_t(const manager_t &)
	{
	}

};

*/

#endif //__MANAGER_H__